name: Release binary

on:
  release:
    types:
      - created

permissions:
  contents: write
  packages: write
jobs:
  build:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
          - linux
          - windows
        goarch:
          - amd64
          - arm64
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Setup go and release
        uses: wangyoucao577/go-release-action@v1.49
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          md5sum: false
